Repository Wits-SG/CGV-Project, pull requests merged in 2023-10, with the labels that each got.

#20 change: constructs add to a local tjs object and then to a scene
  src/constructs/Player.ts
  src/lib/w3ads/Construct.ts
  src/lib/w3ads/Scene.ts
  src/scenes/Sandbox.ts
Labels: enhancement

#21 Add some utility
  src/constructs/Player.ts
  src/lib/w3ads/Project.ts
  src/main.ts
Labels: enhancement

#22 Add interactable objects
  src/constructs/Player.ts
  src/lib/w3ads/PhysicsContext.ts
  src/scenes/Sandbox.ts
Labels: enhancement

#23 fix: jump bug
  src/constructs/Player.ts
Labels: bug

#24 Added some simple documentation
  docs/Constructs.md
  docs/GraphicsContext.md
  docs/PhysicsContext.md
  docs/Projects.md
  docs/Scenes.md
Labels: enhancement

#25 remove: old player construct
  src/player.ts
Labels: bug

#26 add: Interaction interact-optimisation
  src/lib/w3ads/PhysicsContext.ts
Labels: enhancement

#28 add: addFreeStatic
  src/lib/w3ads/PhysicsContext.ts
Labels: bug, enhancement

#29 Interaction Reworkd
  src/constructs/MainLibraryRoom.ts
  src/constructs/Player.ts
  src/constructs/TestConstruct.ts
  src/lib/w3ads/Construct.ts
  src/lib/w3ads/InteractManager.ts
  src/lib/w3ads/PhysicsContext.ts
  src/lib/w3ads/Scene.ts
  src/scenes/Sandbox.ts
Labels: enhancement

#35 Mirror Puzzle
  src/constructs/MirrorRoom.ts
  src/lib/CustomReflector.ts
Labels: enhancement

#39 Main Menu
  index.html
  src/constructs/MainLibraryRoom.ts
  src/lib/w3ads/Project.ts
  src/lib/w3ads/Scene.ts
  src/main.ts
  src/scenes/MainMenu.ts
Labels: enhancement

#42 Main menu fix
  src/scenes/MainMenu.ts
Labels: bug

#43 Added user interface
  src/constructs/CrystalDoor.ts
  src/constructs/MainLibraryRoom.ts
  src/constructs/MirrorRoom.ts
  src/constructs/Music.ts
  src/constructs/Player.ts
  src/constructs/Statues.ts
  src/constructs/TestConstruct.ts
  src/lib/PauseMenu.ts
  src/lib/w3ads/Construct.ts
  src/lib/w3ads/InterfaceContext.ts
  src/lib/w3ads/Project.ts
  src/lib/w3ads/Scene.ts
  src/scenes/MainMenu.ts
  src/scenes/Sandbox.ts
Labels: bug, enhancement

#48 UI rework
  src/constructs/CrystalDoor.ts
  src/constructs/Player.ts
  src/lib/GameOverScreen.ts
  src/lib/PauseMenu.ts
  src/lib/UiComponents.ts
  src/lib/w3ads/InterfaceContext.ts
  src/lib/w3ads/Project.ts
  src/scenes/Level1.ts
  src/scenes/Level2.ts
  src/scenes/Level3.ts
  src/scenes/MainMenu.ts
  src/scenes/Sandbox.ts
Labels: enhancement

#50 add: UI cleanup on end of scene
  src/lib/w3ads/InterfaceContext.ts
  src/lib/w3ads/Scene.ts
  src/scenes/MainMenu.ts
Labels: bug

#51 Change CI
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: enhancement

#52 Player rework
  src/constructs/CrystalDoor.ts
  src/constructs/MainLibraryRoom.ts
  src/constructs/Player.ts
  src/lib/UiComponents.ts
  src/lib/w3ads/InterfaceContext.ts
  src/lib/w3ads/Project.ts
Labels: enhancement

#53 Lectern
  public/assets/Lectern/lectern.gltf
  src/constructs/Lectern.ts
  src/lib/UiComponents.ts
  src/scenes/MainMenu.ts
  src/scenes/Sandbox.ts
Labels: enhancement

#55 fix: Looking at office causes a lagspike
  src/constructs/MainLibraryRoom.ts
  src/lib/w3ads/Project.ts
Labels: bug

#54 fix: UI menus being duplicated on restart by cleaning up event listeners
  src/constructs/Player.ts
Labels: bug

#56 Added Leaderboard
  src/constructs/Lectern.ts
  src/constructs/Player.ts
  src/lib/UI/Controls.ts
  src/lib/UI/Credits.ts
  src/lib/UI/EndLevelMenu.ts
  src/lib/UI/HintMenu.ts
  src/lib/UI/HowToPlay.ts
  src/lib/UI/LevelMenu.ts
  src/lib/UI/MainMenu.ts
  src/lib/UI/PauseMenu.ts
  src/lib/UI/utility.ts
  src/lib/UiComponents.ts
  src/scenes/Level1.ts
  src/scenes/Level2.ts
  src/scenes/Level3.ts
  src/scenes/MainMenu.ts
Labels: enhancement

#57 add: Crystal spawns in random places in office
  src/constructs/OfficeConstruct.ts
Labels: enhancement

#58 add: Prompts - seemingly no perf impact
  src/constructs/Player.ts
Labels: bug, enhancement

#59 Postprocessing
  public/assets/glow.png
  src/constructs/Crystal.ts
  src/constructs/Player.ts
  src/lib/UI/MainMenu.ts
  src/lib/UI/Options.ts
  src/lib/UI/PauseMenu.ts
  src/lib/w3ads/GraphicsContext.ts
  src/lib/w3ads/Project.ts
  src/scenes/MainMenu.ts
Labels: enhancement

#60 Loading
  src/lib/w3ads/Project.ts
  src/main.ts
  src/scenes/Loading.ts
Labels: enhancement

#65 fix: Stop game clock on pause
  src/constructs/Chandeliers.ts
  src/constructs/WallLights.ts
  src/lib/w3ads/Project.ts
  src/scenes/Sandbox.ts
Labels: bug

#66 fix: Sandbox
  src/scenes/Sandbox.ts
Labels: bug

#68 Fix main menu
  src/scenes/MainMenu.ts
Labels: enhancement

#72 Fix: Block layers
  src/constructs/MirrorRoom.ts
Labels: enhancement

#73 office puzzle
  public/assets/cauldron/license.txt
  public/assets/cauldron/scene.bin
  public/assets/cauldron/scene.gltf
  public/assets/cauldron/textures/blinn1_baseColor.png
  public/assets/cauldron/textures/blinn1_metallicRoughness.png
  public/assets/cauldron/textures/blinn1_normal.png
  public/assets/feather/license.txt
  public/assets/feather/scene.bin
  public/assets/feather/scene.gltf
  public/assets/wizard_hat/license.txt
  public/assets/wizard_hat/scene.bin
  public/assets/wizard_hat/scene.gltf
  public/assets/wizard_hat/textures/hat2.1001_baseColor.jpeg
  src/constructs/Balcony.ts
  src/constructs/OfficeConstruct.ts
  src/constructs/Pillar.ts
  src/constructs/Staircase.ts
Labels: enhancement

#75 Music in library
  src/constructs/MainLibraryRoom.ts
  src/constructs/MusicPuzzle.ts
Labels: enhancement

#76 Balancing
  src/constructs/MirrorRoom.ts
  src/constructs/Player.ts
  src/lib/UI/EndLevelMenu.ts
  src/lib/UI/LevelMenu.ts
  src/lib/UI/PauseMenu.ts
Labels: enhancement

#78 New mirror puzzle
  src/constructs/MainLibraryRoom.ts
  src/constructs/MirrorRoom.ts
Labels: enhancement

#79 change: Lower Default FOV
  src/constructs/Player.ts
Labels: bug, enhancement

#80 fix: Account for more than the needed amount of crystals placed
  src/constructs/CrystalDoor.ts
Labels: bug

#82 Add shadows
  src/constructs/MainLibraryRoom.ts
  src/constructs/MusicPuzzle.ts
  src/constructs/Statues.ts
Labels: enhancement

#83 Fixed mirror and added shadows in main menu
  src/constructs/CrystalDoor.ts
  src/constructs/MirrorRoom.ts
  src/lib/CustomReflector.ts
  src/scenes/MainMenu.ts
Labels: bug

#85 Final fixes
  src/constructs/CrystalDoor.ts
  src/constructs/HearthObjects.ts
  src/constructs/MainLibraryRoom.ts
  src/constructs/MusicPuzzle.ts
  src/constructs/Player.ts
  src/lib/CustomReflector.ts
  src/lib/UI/MainMenu.ts
  src/lib/UI/Options.ts
  src/lib/w3ads/GraphicsContext.ts
  src/lib/w3ads/Project.ts
  src/main.ts
  src/scenes/MainMenu.ts
  src/scenes/Sandbox.ts
Labels: bug, enhancement
